const ALL_EVENTS = [
  {
    id: 1,
    date: "2026-06-06",
    start: "17:30",
    end: "20:30",
    name: "The Art of Mending: Manifold Selves in Fabric",
    venue: "Cafe Alma",
    address:
      "888 Innes Avenue, San Francisco, California, 94124, United States",
    lat: 37.7314,
    lng: -122.3732,
    type: "workshop",
    tag: "Workshop/Craft",
    desc: "Reconnect with your creativity, reflect on the many parts of who you are through your own patch pattern, and learn the basics of sewing machines, while being intentional with the material and design – all in a relaxed, collaborative space.",
    url: "https://sfdesignweek.org/event/the-art-of-mending-manifold-selves-in-fabric/",
  },
  {
    id: 2,
    date: "2026-06-06",
    start: "21:00",
    end: "03:00",
    name: "We Are Stories",
    venue: "6th Avenue Skate Park in Golden Gate Park",
    address:
      "6th Avenue Skate Park in Golden Gate Park, Golden Gate Park, San Francisco, CA, 94118, United States",
    lat: 37.7725,
    lng: -122.4641,
    type: "immersive",
    tag: "Immersive/Storytelling",
    desc: "We Are Stories is a public storytelling event based on the idea that we, people, are more than everything we think we are; we are stories. Participants write, cut shapes, attach images, walk through the pages through cut-out gaps, write notes on musical pages, make marks, and alter a human-scale large accordion book.",
    url: "https://sfdesignweek.org/event/we-are-stories/",
  },
  {
    id: 3,
    date: "2026-06-09",
    start: "15:30",
    end: "17:30",
    name: "Design in a post-product world",
    venue: "Whipsaw",
    address: "55 Mississippi, SAN FRANCISCO, California, 94107, United States",
    lat: 37.7628,
    lng: -122.3943,
    type: "talk",
    tag: "Talk/Design Strategy",
    desc: "When capable design tools are in more hands and every product looks the part, visual quality stops being a differentiator — so how do customers tell real design from its imitation? This talk explores what separates the products people return to from the ones they forget.",
    url: "https://sfdesignweek.org/event/design-in-a-post-product-world/",
  },
  {
    id: 4,
    date: "2026-06-09",
    start: "23:30",
    end: "02:00",
    name: "San Francisco Carry Collective",
    venue: "Peak Design HQ",
    address: "2415 3rd St. STE 270, San Francisco, CA, 94107, United States",
    lat: 37.7608,
    lng: -122.3881,
    type: "panel",
    tag: "Panel/Bag Design",
    desc: "Join us at Peak Design’s HQ in the historic American Industrial Center for a night celebrating San Francisco’s rich bag design legacy. Hear directly from local designers in a panel discussion, connect with fellow carry obsessives, and check out a community show-and-tell of favorite bags.",
    url: "https://sfdesignweek.org/event/san-francisco-carry-collective/",
  },
  {
    id: 5,
    date: "2026-06-06",
    start: "18:00",
    end: "01:00",
    name: "NICOLEHOLLIS Collection at Minnesota Street Project",
    venue: "Minnesota Street Project, Gallery 209",
    address:
      "1275 Minnesota Street, San Francisco, California, 94107, United States",
    lat: 37.7552,
    lng: -122.3901,
    type: "exhibition",
    tag: "Exhibition/Craft",
    desc: "Minnesota Street Project will host a pop-up by San Francisco interior design studio NICOLEHOLLIS. The activation is the first public presentation of the NICOLEHOLLIS Collection — a line of limited-edition, artist- and artisan-made objects for the home.",
    url: "https://sfdesignweek.org/event/nicolehollis-collection-at-minnesota-street-project/",
  },
  {
    id: 6,
    date: "2026-06-06",
    start: "20:00",
    end: "21:30",
    name: "Case Study House #26 Open House / House Tour",
    venue: "Case Study House #26",
    address:
      "177 San Marino Drive, San Rafael, California, 94901, United States",
    lat: 37.9863,
    lng: -122.5022,
    type: "open house",
    tag: "Open House/Architecture",
    desc: "Join us during SF Design Week for an exclusive tour of Northern California’s only Case Study House, a 1962 mid-century modern masterpiece nestled in San Rafael representing a pivotal moment in American design history.",
    url: "https://sfdesignweek.org/event/case-study-house-26-open-house-house-tour-1pm/",
  },
  {
    id: 7,
    date: "2026-06-09",
    start: "00:30",
    end: "03:00",
    name: "⌘ + AI + Design: How to prompt like a designer",
    venue: "Digital Garage",
    address: "717 Market St, San Francisco, California, 94103, United States",
    lat: 37.7876,
    lng: -122.4029,
    type: "workshop",
    tag: "Workshop/AI Design",
    desc: "In this hands-on workshop, you'll learn from an ex-Dropbox, award-winning product designer how to prompt like a designer, design styles that convert, metaprompting hacks, and rapid prototyping techniques.",
    url: "https://sfdesignweek.org/event/%e2%8c%98-ai-design-how-to-prompt-like-a-designer/",
  },
  {
    id: 8,
    date: "2026-06-05",
    start: "00:45",
    end: "03:00",
    name: "Bay Locality | The Future Matter: Technological innovation in architectural design and fabrication",
    venue: "Diaspora Hub",
    address: "221 11th, San Francisco, California, 94110, United States",
    lat: 37.7712,
    lng: -122.4132,
    type: "talk",
    tag: "Talk/Architecture",
    desc: "A conversation on how technological innovation in architectural design and fabrication creates new possibilities for architecture deeply rooted in place — examining the poetics of Bay Area locality through design, material intelligence, and advanced manufacturing.",
    url: "https://sfdesignweek.org/event/bay-locality-the-future-matter/",
  },
  {
    id: 9,
    date: "2026-06-05",
    start: "22:00",
    end: "00:00",
    name: "SF Design Week Innovation Awards Recipient Social (Recipient Invite Only)",
    venue: "Lumens",
    address:
      "724 Battery St First Floor, San Francisco, CA, 94111, United States",
    lat: 37.7972,
    lng: -122.4014,
    type: "social",
    tag: "Social/Awards",
    desc: "A celebratory afternoon honoring the studios, teams, and designers whose work received top recognition from our esteemed jury for this year’s awards. Co-presented by Lumens and Flowers Vineyards & Winery.",
    url: "https://sfdesignweek.org/event/sf-design-week-innovation-awards-recipient-social/",
  },
  {
    id: 10,
    date: "2026-06-05",
    start: "01:00",
    end: "05:00",
    name: "Gantri Wireless Launch Party, Celebrating Pride Month",
    venue: "Gantri The Shop",
    address: "320 10th St, San Francisco, California, 94103, United States",
    lat: 37.7718,
    lng: -122.4121,
    type: "social",
    tag: "Social/Launch Party",
    desc: "Be the first to see our new wireless collection, designed by Ammunition. Join us in San Francisco for an evening of drinks, music, and a first look at the collection, alongside an immersive installation by Sheki Cicelsky in celebration of Pride Month.",
    url: "https://sfdesignweek.org/event/gantri-wireless-launch-party-celebrating-pride-month/",
  },
  {
    id: 11,
    date: "2026-06-09",
    start: "01:30",
    end: "03:00",
    name: "Designing the Future Designer: A Speculative Workshop on Identity, Agency, and Craft in an AI-First World",
    venue: "California College of the Arts, Novack Hub for Creative Citizens",
    address: "145 Hooper Street, San Francisco, 94107, United States",
    lat: 37.7668,
    lng: -122.3995,
    type: "workshop",
    tag: "Workshop/AI Future",
    desc: "In this hands-on workshop, Elizabeth Glenewinkel and Justin Rheinfrank pose provocations on the future of design for you to challenge, debunk or embrace. This session is part sparring match, part design sprint.",
    url: "https://sfdesignweek.org/event/designing-the-future-designer-a-speculative-workshop-on-identity-agency-and-craft-in-an-ai-first-world/",
  },
  {
    id: 12,
    date: "2026-06-05",
    start: "22:30",
    end: "01:00",
    name: "Climbing for Everyone: An Introduction to Route Setting with Touchstone Climbing",
    venue: "Dogpatch Boulders",
    address: "2573 3rd st., San Francisco, California, 94107, United States",
    lat: 37.7573,
    lng: -122.3879,
    type: "workshop",
    tag: "Workshop/Experience Design",
    desc: "This event introduces designers to the world of route setting — part craft, part performance design, part puzzle-making — and opens a conversation about what our disciplines can learn from each other.",
    url: "https://sfdesignweek.org/event/climbing-for-everyone-an-introduction-to-route-setting-with-touchstone-climbing/",
  },
  {
    id: 13,
    date: "2026-06-05",
    start: "00:30",
    end: "03:30",
    name: "Armadillo x Figwaspe: A Meridian Tasting Experience (Sold Out)",
    venue: "Armadillo",
    address: "3695 Sacramento Street, San Francisco, CA, 94118, United States",
    lat: 37.7874,
    lng: -122.4532,
    type: "immersive",
    tag: "Immersive/Culinary Art",
    desc: "Join us for an exclusive first preview of Meridian, Armadillo‘s forthcoming collection, through an intimate tasting experience by culinary artist FIGWASPE. Created in partnership for SF Design Week, the evening translates the inspiration behind the collection into flavor, texture, and form.",
    url: "https://sfdesignweek.org/event/armadillo-x-figwaspe-a-taste-of-meridian/",
  },
  {
    id: 14,
    date: "2026-06-06",
    start: "22:30",
    end: "01:30",
    name: "Animation Challenge: Exquisite Corpse",
    venue: "The Nook",
    address:
      "1242 Market St Floor 2, San Francisco, California, 94102, United States",
    lat: 37.7786,
    lng: -122.4143,
    type: "workshop",
    tag: "Workshop/Animation",
    desc: "Global online community and local meetup group celebrating the motion graphics industry are teaming up to host a special event — a live collaboration where local artists are challenged to animate on the fly in front of a live audience.",
    url: "https://sfdesignweek.org/event/animation-challenge-exquisite-corpse/",
  },
  {
    id: 15,
    date: "2026-06-06",
    start: "00:30",
    end: "03:30",
    name: "Official Party: San Francisco Design Week Celebrating 20 Years!",
    venue: "Pier 24",
    address: "Pier 24, Pier 24, San Francisco, CA, 94105, United States",
    lat: 37.7909,
    lng: -122.3878,
    type: "social",
    tag: "Social/Party",
    desc: "This event is the largest gathering during San Francisco Design Week: we’ll come together under one roof and celebrate all things design week! Enjoy local wines, themed cocktails, matcha, and a live DJ set.",
    url: "https://sfdesignweek.org/event/official-party-san-francisco-design-week/",
  },
  {
    id: 16,
    date: "2026-06-06",
    start: "22:00",
    end: "23:30",
    name: "Case Study House #26 Open House / House Tour (3pm session)",
    venue: "Case Study House #26",
    address:
      "177 San Marino Drive, San Rafael, California, 94901, United States",
    lat: 37.9863,
    lng: -122.5022,
    type: "open house",
    tag: "Open House/Architecture",
    desc: "Join us during SF Design Week for an exclusive tour of Northern California’s only Case Study House, a 1962 mid-century modern masterpiece nestled in San Rafael. Walk through perfectly preserved spaces that have graced the pages of numerous architecture publications.",
    url: "https://sfdesignweek.org/event/case-study-house-26-open-house-house-tour-3pm/",
  },
  {
    id: 17,
    date: "2026-06-06",
    start: "18:00",
    end: "00:00",
    name: "Marinship Open Studios",
    venue: "Marinship Studios",
    address: "265 Gate 5 Rd, Sausalito, California, 94965, United States",
    lat: 37.8694,
    lng: -122.4965,
    type: "open studio",
    tag: "Open Studio/Art & Craft",
    desc: "Discover the creative visions of Sausalito’s Marinship Studios artists at a unique Open Studio event. Step into the studios, engage with the artists, and gain insight into their creative processes and sources of inspiration.",
    url: "https://sfdesignweek.org/event/marinship-open-studios-2/",
  },
  {
    id: 18,
    date: "2026-06-05",
    start: "20:00",
    end: "00:00",
    name: "Dynamic Minds, Brilliant Inspiration: Sausalito Design and Architecture Studio Study Tour",
    venue: "Various Studios",
    address: "Sausalito Waterfront, Sausalito, CA, 94965, United States",
    lat: 37.8591,
    lng: -122.4853,
    type: "open studio",
    tag: "Open Studio/Architecture",
    desc: "Join us for an afternoon immersed in the studios of two interior design firms and one architectural firm: The Office of Charles de Lisle, Studio Collins Weir, and Luca Pignata Studio open their doors in Sausalito.",
    url: "https://sfdesignweek.org/event/dynamic-minds-brilliant-inspiration-sausalito-design-and-architecture-studio-study-tour/",
  },
  {
    id: 19,
    date: "2026-06-07",
    start: "21:00",
    end: "00:00",
    name: "The Thought Experiment",
    venue: "California College of the Arts, Novack Hub for Creative Citizens",
    address: "145 Hooper Street, San Francisco, CA, 94107, United States",
    lat: 37.7668,
    lng: -122.3995,
    type: "immersive",
    tag: "Immersive/Art & Tech",
    desc: "The installation uses EEG to translate the neural activity of participants into the environment around them in real time. What you encounter depends on who is inside with you, and which future you find yourselves inside together.",
    url: "https://sfdesignweek.org/event/the-thought-experiment/",
  },
  {
    id: 20,
    date: "2026-06-07",
    start: "01:00",
    end: "05:00",
    name: "Layered Perspectives: A Women in Design SF Showcase",
    venue: "Gantri The Shop",
    address: "320 10th Street, San Francisco, California, 94103, United States",
    lat: 37.7718,
    lng: -122.4121,
    type: "exhibition",
    tag: "Exhibition/Showcase",
    desc: "Women in Design SF (WID) is teaming up with Gantri to host our third annual showcase at SF Design Week exhibiting works from women, nonbinary, and gender-expansive designers from around the Bay Area.",
    url: "https://sfdesignweek.org/event/layered-perspectives-a-women-in-design-sf-showcase/",
  },
  {
    id: 21,
    date: "2026-06-05",
    start: "00:00",
    end: "03:00",
    name: "ADRIFT. AFLOAT. DRY-DOCKED. | A curatorial tour that combines maritime heritage & boat-themed work by 3 local artists",
    venue: "Bldg 12, Pier 70",
    address:
      "1070 Maryland @ 22nd St, San Francisco, California, 94107, United States",
    lat: 37.7602,
    lng: -122.3846,
    type: "exhibition",
    tag: "Exhibition/Tour",
    desc: "Set within the soaring public atrium of Building 12 at Pier 70, this exhibition pays homage to the site’s shipbuilding past while exploring the human condition through a nautical lens with a tour led by Sarah Stangle.",
    url: "https://sfdesignweek.org/event/adrift-afloat-dry-docked-a-curatorial-tour-that-combines-maritime-heritage-boat-themed-work-by-3-local-artists/",
  },
  {
    id: 22,
    date: "2026-06-06",
    start: "18:00",
    end: "20:15",
    name: "From Inspiration to Pattern: a hands-on blockprint workshop",
    venue: "Seema Krish Studio",
    address:
      "185 Arkansas street, San Francisco, California, 94107, United States",
    lat: 37.7621,
    lng: -122.3984,
    type: "workshop",
    tag: "Workshop/Textiles",
    desc: "Please join textile designer Seema Krish and her team for an immersive, creative event exploring the art of traditional handblock printing. Create your own hand-printed tote bag using Seema’s array of wood blocks.",
    url: "https://sfdesignweek.org/event/from-inspiration-to-pattern-a-hands-on-blockprint-workshop/",
  },
  {
    id: 23,
    date: "2026-06-05",
    start: "00:30",
    end: "03:30",
    name: "Designing the Space Around Your Ears (SAYE)",
    venue: "The Jay, Autograph Collection Hotel",
    address: "433 Clay St., San Francisco, California, 94111, United States",
    lat: 37.7954,
    lng: -122.4005,
    type: "panel",
    tag: "Panel/Music & Design",
    desc: "Enjoy a live musical performance and conversation about how the most powerful cultural commodity is designed from creation to consumption. This panel brings together voices from across the music industry.",
    url: "https://sfdesignweek.org/event/designing-music-panel-discussion-and-live-performance/",
  },
  {
    id: 24,
    date: "2026-06-06",
    start: "20:00",
    end: "00:00",
    name: "Dynamic Minds, Brilliant Inspiration: SoMa Architecture and Design Studio Study Tour",
    venue: "Various Studios",
    address: "1022 Natoma Street, San Francisco, 94103, United States",
    lat: 37.7761,
    lng: -122.4112,
    type: "open studio",
    tag: "Open Studio/Architecture",
    desc: "Join us for a rare afternoon inside two of San Francisco’s most accomplished and internationally admired studios — Stanley Saitowitz | Natoma Architects and BAMO — in the city’s SoMa district.",
    url: "https://sfdesignweek.org/event/dynamic-minds-brilliant-inspiration-soma-architecture-and-design-studio-study-tour/",
  },
  {
    id: 25,
    date: "2026-06-09",
    start: "00:00",
    end: "03:00",
    name: "JB Blunk: A look inside his work and legacy with Mariah Nielson",
    venue: "Minnesota Street Flyover",
    address: "878 20th St, San Francisco, CA, 94107, United States",
    lat: 37.7592,
    lng: -122.3908,
    type: "talk",
    tag: "Talk/Art & Design",
    desc: "Join us for a glimpse inside the JB Blunk Estate and Blunk Space in this lecture by Mariah Nielson, Blunk’s daughter, curator, and design historian, exploring his work with raw, salvaged materials.",
    url: "https://sfdesignweek.org/event/jb-blunk-a-look-inside-his-work-and-legacy-with-mariah-nielson/",
  },
  {
    id: 26,
    date: "2026-06-05",
    start: "00:00",
    end: "02:15",
    name: "Event CANCELLED: CAD, Design + AI",
    venue: "Groundfloor SF",
    address: "455 Valencia, San Francisco, California, 94103, United States",
    lat: 37.7656,
    lng: -122.4218,
    type: "talk",
    tag: "Talk/AI & CAD",
    desc: "***THIS EVENT HAS BEEN CANCELED DUE TO UNFORESEEN CIRCUMSTANCES*** AI is rapidly changing design, raising deep questions about what it means to be a designer, what it means to design, and what roles people take in relationship to AI.",
    url: "https://sfdesignweek.org/event/cad-design-ai/",
  },
  // June 9
  {
    id: 27,
    date: "2026-06-09",
    start: "18:30",
    end: "20:45",
    name: "Art Swap: Celebrating Multitudes",
    venue: "FLAX Art & Design — Fort Mason",
    address: "2 Marina Blvd, San Francisco",
    lat: 37.8065,
    lng: -122.4278,
    type: "social",
    tag: "Social/Art",
    desc: "A co-created gallery and art-trading happy hour from Coqtail Hour. Every guest arrives with a hand-sized piece of their own art. The gallery becomes a trading floor — swap art, meet makers, and leave with someone else's work. Hosted at the historic FLAX Art & Design.",
    url: "https://sfdesignweek.org/event/art-swap-celebrating-multitudes/",
  },
  // June 10
  {
    id: 28,
    date: "2026-06-10",
    start: "14:00",
    end: "15:30",
    name: "Agentic AI Design Workshop: From Play to Prototype",
    venue: "California College of the Arts",
    address: "145 Hooper Street, San Francisco",
    lat: 37.7714,
    lng: -122.3957,
    type: "workshop",
    tag: "Workshop",
    desc: "Spend 90 minutes at CCA workshopping the full arc of designing an AI agent — Enact, Author, Deploy. Small groups bodystorm a scenario, write behavioral rules, and see their agent run live on Agent Studio. No coding required. $15 fee.",
    url: "https://sfdesignweek.org/event/agentic-ai-design-workshop-from-play-to-prototype/",
  },
  {
    id: 29,
    date: "2026-06-10",
    start: "15:00",
    end: "17:00",
    name: "Human-Centered Design in an AI World",
    venue: "Google",
    address: "345 Spear St, San Francisco",
    lat: 37.7892,
    lng: -122.3927,
    type: "talk",
    tag: "Talk",
    desc: 'As AI evolves, human skills like judgment, creativity, and clarity of intent are more critical than ever. A discussion on how designers are becoming "AI fluent" — treating models as strategic partners while keeping human taste as the essential filter. No walk-ins.',
    url: "https://sfdesignweek.org/event/human-centered-design-in-an-ai-world/",
  },
  {
    id: 30,
    date: "2026-06-10",
    start: "16:00",
    end: "18:00",
    name: "Designing a Creative Life: A Design & Architecture Gathering at CCA",
    venue: "California College of the Arts",
    address: "145 Hooper Street, San Francisco",
    lat: 37.7714,
    lng: -122.3957,
    type: "social",
    tag: "Social",
    desc: 'Alumni, faculty, staff, and friends gather to reconnect and consider what it means to carry a CCA creative education into the world. "Call the Archive" audio story recording, "One Object, Many Stories" exhibition, cocktails and hors d\'oeuvres.',
    url: "https://sfdesignweek.org/event/designing-a-creative-life-a-design-and-architecture-gathering-at-cca/",
  },
  {
    id: 31,
    date: "2026-06-10",
    start: "17:00",
    end: "20:00",
    name: "Celebrate SF Ingenuity and Design at Stagecoach Greens",
    venue: "Stagecoach Greens & Spark Gardens",
    address: "1379 4th Street, San Francisco",
    lat: 37.7598,
    lng: -122.39,
    type: "social",
    tag: "Social",
    desc: "SFDW meetup at Stagecoach Greens Mini-Golf, a playful story-driven course designed and fabricated by One Hat One Hand. VIP hang with drinks, bites, and networking in the Spark Gardens cabanas — play a hole, toss some cornhole bags, or just relax.",
    url: "https://sfdesignweek.org/event/celebrate-san-francisco-ingenuity-and-design-at-stagecoach-greens-mini-golf/",
  },
  {
    id: 32,
    date: "2026-06-10",
    start: "17:00",
    end: "20:00",
    name: "Chair Exploded: Installation Debut and Talk",
    venue: "Humanscale Showroom SF",
    address: "10 Jackson Street, San Francisco",
    lat: 37.7979,
    lng: -122.399,
    type: "exhibition",
    tag: "Exhibition/Talk",
    desc: "Artist Elijah Ezralow's \"Chair Exploded\" deconstructs Humanscale seating to reveal function, geometry, and material of each component. At 6pm, Elijah gives a deep dive into Niels Diffrient's iconic ergonomic works, from prototype to product.",
    url: "https://sfdesignweek.org/event/the-humanscale-chair-exploded-installation-opening-and-talk/",
  },
  {
    id: 33,
    date: "2026-06-10",
    start: "17:00",
    end: "20:00",
    name: "Alicia Escott at Teknion: Artist Talk and Conversation",
    venue: "Teknion",
    address: "2 Bryant Street, San Francisco",
    lat: 37.7895,
    lng: -122.3905,
    type: "talk",
    tag: "Artist Talk",
    desc: "Artist Alicia Escott, in conversation with Marthine Satris, speaks about her interdisciplinary practice and ongoing collaboration with wildflower seeds — Metabolic Rifts and Domestic Interiors. Drinks and small bites from 5pm, talk at 6pm.",
    url: "https://sfdesignweek.org/event/alicia-escott-artist-talk-and-conversation/",
  },
  {
    id: 34,
    date: "2026-06-10",
    start: "17:45",
    end: "18:30",
    name: "A Week Inside an AI-Native Design Team",
    venue: "Gamma",
    address: "350 Rhode Island, San Francisco",
    lat: 37.7679,
    lng: -122.402,
    type: "talk",
    tag: "Talk",
    desc: "Head of Design and an AI-native designer at Gamma on how every designer ships prototypes from Claude Code — skills written, connectors relied on, how to gather context before touching a pixel, and what a real prompting loop looks like. Half talk, half Q&A.",
    url: "https://sfdesignweek.org/event/a-week-inside-an-ai-native-design-team/",
  },
  {
    id: 35,
    date: "2026-06-10",
    start: "18:00",
    end: "20:00",
    name: "Wellness x Design",
    venue: "Mokume Design Studio",
    address: "2169 Folsom St, San Francisco",
    lat: 37.7568,
    lng: -122.415,
    type: "talk",
    tag: "Panel",
    desc: "Mokume Design Studio's Jennifer Downing and Dr. Hemalee Patel on science-backed wellness design — circadian rhythm-responsive environments, biophilic strategies, thermotherapy, and designing spaces that support physical and mental health.",
    url: "https://sfdesignweek.org/event/wellness-x-design/",
  },
  {
    id: 36,
    date: "2026-06-10",
    start: "18:00",
    end: "20:00",
    name: "Noz Nozawa x Flexform: Craft as Culture",
    venue: "Flexform San Francisco",
    address: "145 Rhode Island St, San Francisco",
    lat: 37.7693,
    lng: -122.4027,
    type: "talk",
    tag: "Talk",
    desc: "Interior designer Noz Nozawa and Pete Rodway explore how design becomes a lens for personal identity — restraint, craft, and material sensitivity, in dialogue across Japanese ancestry and Italian craftsmanship.",
    url: "https://sfdesignweek.org/event/noz-nozawa-x-flexform-craft-as-culture-a-personal-dialogue-with-identity-and-design/",
  },
  {
    id: 37,
    date: "2026-06-10",
    start: "18:00",
    end: "22:00",
    name: "Ciel Turns 7: A Living Open House",
    venue: "Ciel Creative Space",
    address: "2611 Eighth Street, Berkeley",
    lat: 37.8602,
    lng: -122.2884,
    type: "social",
    tag: "Open House",
    desc: 'Ciel Creative Space celebrates 7 years with a choose-your-own-adventure through immersive studio activations — a fashion show bringing "multitudes" to life, an art & tech exhibition, next-era headshots, music, and connections that actually stick.',
    url: "https://sfdesignweek.org/event/ciel-turns-7-a-living-open-house/",
  },
  {
    id: 38,
    date: "2026-06-10",
    start: "18:30",
    end: "20:45",
    name: "Me, You, and a Robot",
    venue: "PA Consulting",
    address: "517 York Street, San Francisco",
    lat: 37.7538,
    lng: -122.4168,
    type: "talk",
    tag: "Panel",
    desc: "Visions of robots span a wide spectrum — helpful partners to unsettling replacements. Join PA Consulting to define the terms and question them. Surgical systems, warehouse machines, companions, autonomous vehicles: the role of robots is open for debate.",
    url: "https://sfdesignweek.org/event/me-you-and-a-robot/",
  },
  // June 11
  {
    id: 39,
    date: "2026-06-11",
    start: "15:00",
    end: "18:00",
    name: "Connection, Cocktails and Collage with Sköna",
    venue: "Sköna HQ",
    address: "147 Natoma St, San Francisco",
    lat: 37.7876,
    lng: -122.3979,
    type: "social",
    tag: "Social",
    desc: "In honor of the theme Multitudes, Sköna explores how Bay Area diversity informs creativity through a collaborative collage wall. Add a drawing, quote, or thought that reflects your life in the Bay Area. Magazines, craft supplies, snacks, and beverages provided.",
    url: "https://sfdesignweek.org/event/connection-cocktails-and-collage-with-skona/",
  },
  {
    id: 40,
    date: "2026-06-11",
    start: "15:00",
    end: "18:00",
    name: "More Than One Thing: Celebrating Creative Multitudes",
    venue: "Creativity Explored",
    address: "3245 16th St, San Francisco",
    lat: 37.7641,
    lng: -122.4271,
    type: "social",
    tag: "Social",
    desc: "Happy hour and open studio at Creativity Explored, a pioneering art studio partnering with artists with developmental disabilities. Painters, ceramicists, storytellers, designers — each bringing distinct perspectives. Natural wine, light bites from Bi-Rite.",
    url: "https://sfdesignweek.org/event/more-than-one-thing-celebrating-creative-multitudes/",
  },
  {
    id: 41,
    date: "2026-06-11",
    start: "15:00",
    end: "18:00",
    name: "Brainy Bold: Design as a Model for Cognition",
    venue: "Space DanzArte",
    address: "1067 Market St, San Francisco",
    lat: 37.7751,
    lng: -122.4183,
    type: "exhibition",
    tag: "Exhibition",
    desc: "A modular installation of printed matter, visual grids, garments, and conceptual frameworks exploring how structure, repetition, and visual language shape perception and behavior. Part exhibition, part study space, part quiet provocation.",
    url: "https://sfdesignweek.org/event/brainy-bold-design-as-a-model-for-cognition/",
  },
  {
    id: 42,
    date: "2026-06-11",
    start: "15:30",
    end: "17:00",
    name: "Hand-Printed vs Digital: Textile Craftsmanship",
    venue: "Cloth Edition Printshop",
    address: "705 Cesar Chavez Street, San Francisco",
    lat: 37.7488,
    lng: -122.4047,
    type: "studio",
    tag: "Demo/Talk",
    desc: "Textile designer Anne Kirk and printer Ryan Harrison discuss traditional hand printed textiles, working with master craftspeople, and the value of handprinted versus digital textile designs. Explore the facility and participate in printing.",
    url: "https://sfdesignweek.org/event/hand-printed-vs-digital-textile-craftsmanship-at-cloth-edition-printshop/",
  },
  {
    id: 43,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Connecting the Dots",
    venue: "Unbox Product Design",
    address: "364 11th Street, San Francisco",
    lat: 37.7712,
    lng: -122.4141,
    type: "studio",
    tag: "Open Studio",
    desc: "Open studio at Unbox, a boutique firm in SoMa that partners with startups and disruptors to bring market-ready solutions to life. Behind-the-scenes look at how they deliver big impact across complex projects. Refreshments, snacks, music, giveaways.",
    url: "https://sfdesignweek.org/event/connecting-the-dots/",
  },
  {
    id: 44,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Whipsaw Open Studio",
    venue: "Whipsaw",
    address: "55 Mississippi, San Francisco",
    lat: 37.7668,
    lng: -122.3955,
    type: "studio",
    tag: "Open Studio",
    desc: "Step inside Whipsaw's Potrero Hill studio — a light-filled, industrial-chic space with an ever-growing product gallery. Meet the team behind 20+ years of product design.",
    url: "https://sfdesignweek.org/event/whipsaw-open-studio-3/",
  },
  {
    id: 45,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "ORCA SF Open Studio",
    venue: "ORCA Showroom",
    address: "2422 3rd Street, San Francisco",
    lat: 37.7579,
    lng: -122.3892,
    type: "studio",
    tag: "Open Studio",
    desc: "First look at ORCA's new Dogpatch showroom. Meet founder and principal Molly Sedlacek and see materials in person. ORCA is a female-founded landscape design studio using plants and materials in their rawest form to re/connect humans to the earth.",
    url: "https://sfdesignweek.org/event/orca-sf-open-studio/",
  },
  {
    id: 46,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Where Design Begins: An Open Exhibition by Vizcom",
    venue: "Vizcom",
    address: "488 Bryant St, San Francisco",
    lat: 37.7795,
    lng: -122.397,
    type: "exhibition",
    tag: "Exhibition",
    desc: "Closing night of Vizcom's Makerspace exhibition. See how designers across automotive, fashion, lighting, and architecture integrate AI. Hands-on demo stations, live fabrication, and a prompted design challenge.",
    url: "https://sfdesignweek.org/event/where-design-begins-an-open-exhibition-by-vizcom/",
  },
  {
    id: 47,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Design + Build — Open Studio",
    venue: "Mokume Design Studio",
    address: "2169 Folsom St, San Francisco",
    lat: 37.7568,
    lng: -122.415,
    type: "studio",
    tag: "Open Studio",
    desc: "Shared studio of Mokume Design Studio, Katherine Tincher Design, and Phase2 Builders — pulling out mockups, material boards, and recent projects with local vendors. Cocktails, bites, and good conversation.",
    url: "https://sfdesignweek.org/event/design-build-open-studio/",
  },
  {
    id: 48,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "How We Prompt",
    venue: "Gamma",
    address: "350 Rhode Island, San Francisco",
    lat: 37.7679,
    lng: -122.402,
    type: "studio",
    tag: "Open Studio",
    desc: "Gamma's entire brand system runs on carefully-tuned Midjourney srefs and profiles. Come see the library, meet the builders, and sit down with image models to prompt something of your own. Bring a project or start one here.",
    url: "https://sfdesignweek.org/event/how-we-prompt/",
  },
  {
    id: 49,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Now Studio Open House",
    venue: "Now Studio",
    address: "2309 Bryant Street, San Francisco",
    lat: 37.754,
    lng: -122.4083,
    type: "studio",
    tag: "Open Studio",
    desc: "Now Studio opens its doors for SF Design Week Studio Crawl — explore latest work, meet the team, and experience what makes this nimble SF industrial design agency's approach distinct. Refreshments and light snacks provided.",
    url: "https://sfdesignweek.org/event/now-studio-open-house-2/",
  },
  {
    id: 50,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Punto 3 Launch, by Colección Estudio",
    venue: "Colección Estudio Showroom",
    address: "273 Church St, San Francisco",
    lat: 37.7679,
    lng: -122.4289,
    type: "social",
    tag: "Social/Exhibition",
    desc: "Punto 3's first North American presentation — an evening of design, conversation, and mezcal cocktails celebrating a new platform for international emergent design. See Rehearsals for the Future, the inaugural exhibition from the Punto 3 mentorship program.",
    url: "https://sfdesignweek.org/event/punto-3-launch-by-coleccion-estudio/",
  },
  {
    id: 51,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Our Robots Don't Party. We Do.",
    venue: "NewDealDesign",
    address: "333 Bryant St, San Francisco",
    lat: 37.7815,
    lng: -122.397,
    type: "studio",
    tag: "Open Studio",
    desc: "NewDealDesign — where humans design for AI — opens their studio for one night. Drinks, snacks, a DJ, games, and interactive moments. Meet designers and engineers, hear their stories, and see the space where the magic gets made.",
    url: "https://sfdesignweek.org/event/our-robots-dont-party-we-do/",
  },
  {
    id: 52,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Studio O+A Studio Crawl",
    venue: "Studio O+A",
    address: "452 Tehama Street, San Francisco",
    lat: 37.7827,
    lng: -122.399,
    type: "studio",
    tag: "Open Studio",
    desc: "Happy hour in the Studio O+A studio during the crawl. Take a peek behind the curtain, meet other designers, and engage in an evolving dialogue at the intersection of disciplines.",
    url: "https://sfdesignweek.org/event/studio-oa-studio-crawl/",
  },
  {
    id: 53,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Living Forms: A Biomorphic Studio Crawl",
    venue: "Creative C.O.M.A.",
    address: "40 Rondel Place, San Francisco",
    lat: 37.7557,
    lng: -122.4167,
    type: "exhibition",
    tag: "Exhibition",
    desc: "Three artists explore materiality, form, and transformation through a biomorphic lens — painting, sculptural ceramics, and immersive installation alongside furniture echoing cellular, botanical, and anatomical forms. Brief welcome at 7pm; artists in residence throughout.",
    url: "https://sfdesignweek.org/event/living-forms-a-biomorphic-studio-crawl-at-creative-c-o-m-a/",
  },
  {
    id: 54,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Delve — Open Studio",
    venue: "Delve",
    address: "2225 3rd St, San Francisco",
    lat: 37.7575,
    lng: -122.3888,
    type: "studio",
    tag: "Open Studio",
    desc: "Open house at Delve — multidisciplinary product design and development. Meet the team, explore the studio, and get an inside look at how they define, envision, and develop innovations that make an impact. Food, drinks, and a few surprises.",
    url: "https://sfdesignweek.org/event/delve-open-studio/",
  },
  {
    id: 55,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Huge Design Studio Crawl",
    venue: "Huge Design",
    address: "1082 Howard Street, San Francisco",
    lat: 37.7786,
    lng: -122.4086,
    type: "studio",
    tag: "Open Studio",
    desc: "15 years designing for GoPro, Google, Therabody, and Bowers & Wilkins — for one night Huge opens their SoMa studio. Wander the space, poke at prototypes, and talk shop with the team. No presentations, no agenda.",
    url: "https://sfdesignweek.org/event/huge-design-studio-crawl-sfdw-2026/",
  },
  {
    id: 56,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "Nanu Studio Crawl",
    venue: "Nanu",
    address: "1450 Mariposa Street, San Francisco",
    lat: 37.7614,
    lng: -122.3943,
    type: "studio",
    tag: "Open Studio",
    desc: "Behind the scenes at Nanu, a small SF studio where two designers create objects that make time feel more tangible. See what's on the workbench and how things come together.",
    url: "https://sfdesignweek.org/event/nanu-studio-crawl-26/",
  },
  {
    id: 57,
    date: "2026-06-11",
    start: "18:00",
    end: "21:00",
    name: "PACT Open Studio",
    venue: "Pact Studio",
    address: "1300 S Van Ness Ave, San Francisco",
    lat: 37.7489,
    lng: -122.4179,
    type: "studio",
    tag: "Open Studio",
    desc: "PACT, the boutique brand identity and strategy studio behind this year's SFDW theme, opens their doors. Swing by, grab a drink, and talk shop — branding, strategy, the state of design, whatever you're into. Good people, good conversation, no agenda.",
    url: "https://sfdesignweek.org/event/pact-open-studio/",
  },
  {
    id: 58,
    date: "2026-06-11",
    start: "20:30",
    end: "23:00",
    name: "STEEP: An Immersive Tea Lounge",
    venue: "AIDA — 388 Beale St Penthouse",
    address: "388 Beale Street Penthouse, San Francisco",
    lat: 37.789,
    lng: -122.3921,
    type: "social",
    tag: "Immersive",
    desc: "An evening at the intersection of visual art, sound, scent, and craft. Effervescent tea and cocktail pairings born from immersive projections, scent installations, and lush bites overlooking the Bay Bridge. Location shared with ticket holders 24 hours before.",
    url: "https://sfdesignweek.org/event/steep-an-immersive-tea-lounge/",
  },
  // June 12
  {
    id: 59,
    date: "2026-06-12",
    start: "13:00",
    end: "15:30",
    name: "AI as Your Design Partner (Not Your Replacement)",
    venue: "Shipt",
    address: "535 Mission Street, San Francisco",
    lat: 37.7886,
    lng: -122.3974,
    type: "workshop",
    tag: "Workshop",
    desc: "Hands-on workshop exploring how generative AI can augment the design thinking process while keeping human insight at the center. Small groups apply AI across ideation, synthesis, and concept development — no deep technical experience required.",
    url: "https://sfdesignweek.org/event/ai-as-your-design-partner-not-your-replacement/",
  },
  {
    id: 60,
    date: "2026-06-12",
    start: "14:00",
    end: "16:00",
    name: "Pop-Up Art Show at IA's San Francisco Studio",
    venue: "IA Interior Architects",
    address: "500 Sansome Street, San Francisco",
    lat: 37.7965,
    lng: -122.4016,
    type: "exhibition",
    tag: "Exhibition",
    desc: "IA's newly completed double-height ground-level studio as canvas for creative expression — local artists showcase imagery celebrating San Francisco community, creativity, and the city's art and design community.",
    url: "https://sfdesignweek.org/event/pop-up-art-show-at-ias-san-francisco-studio/",
  },
  {
    id: 61,
    date: "2026-06-12",
    start: "15:00",
    end: "17:00",
    name: "Women Designing San Francisco",
    venue: "Marigold SF",
    address: "2681 21st Street, San Francisco",
    lat: 37.7566,
    lng: -122.4229,
    type: "talk",
    tag: "Panel",
    desc: "Past, Present, Future — a salon-style gathering with Jennifer Sonderby (CCA), Megan Wernetti (Heath Ceramics), Nicole Krasinski (State Bird Provision), Arianna Orland (Meta), and Trina Robinson (Artist & CCA Faculty), celebrating women building SF's creative community.",
    url: "https://sfdesignweek.org/event/women-designing-san-francisco/",
  },
  {
    id: 62,
    date: "2026-06-12",
    start: "16:00",
    end: "18:00",
    name: "Keeping Up with Gen Z: How EdTech Designs for an Ever-Evolving Generation",
    venue: "Quizlet HQ",
    address: "123 Townsend St, San Francisco",
    lat: 37.7804,
    lng: -122.3927,
    type: "talk",
    tag: "Fireside Chat",
    desc: "Quizlet's design and research team shares how they stay embedded in Gen Z students' lives — from daily Discord communities to co-design sessions — joined by design leaders from across EdTech for a conversation on designing for a generation in constant motion.",
    url: "https://sfdesignweek.org/event/keeping-up-with-gen-z-how-edtech-designs-for-an-ever-evolving-generation/",
  },
  {
    id: 63,
    date: "2026-06-12",
    start: "16:30",
    end: "18:30",
    name: "The Future of Home Robotics",
    venue: "Box Clever",
    address: "285 7th St, San Francisco",
    lat: 37.7744,
    lng: -122.4115,
    type: "talk",
    tag: "Talk",
    desc: "Public reveal of the future of home robotics by Box Clever x Weave Robotics. Meet team leaders, learn about their home-first design approach, food and networking, plus a raffle for Box Clever products worth $3000+.",
    url: "https://sfdesignweek.org/event/the-future-of-home-robotics-introduced-by-box-clever-x-weave-robotics/",
  },
  {
    id: 64,
    date: "2026-06-12",
    start: "17:00",
    end: "18:00",
    name: "Erica Tanov: Celebrating a Life in Design",
    venue: "Erica Tanov Atelier",
    address: "1808 Fifth Street, Berkeley",
    lat: 37.8599,
    lng: -122.2889,
    type: "talk",
    tag: "Talk",
    desc: "Designer Erica Tanov in conversation with design writer Diane Dorrans Saeks — exploring creative collaboration, sources of inspiration, and 35 years building a design world guided by natural beauty. Illustrated presentation of interiors, textiles, and artist collaborations.",
    url: "https://sfdesignweek.org/event/erica-tanov-celebrating-a-life-in-design/",
  },
  {
    id: 65,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Evening Reception — PLUME by Kristin Victoria Barron",
    venue: "The Future Perfect",
    address: "3085 Sacramento Street, San Francisco",
    lat: 37.7887,
    lng: -122.448,
    type: "exhibition",
    tag: "Exhibition",
    desc: "A body of work exploring the archetypal language of the subconscious through carefully patinated sculptures. Incorporating functional lighting, the works evoke illumination as something ethereal — as if each piece operates as a threshold between dimensions.",
    url: "https://sfdesignweek.org/event/evening-reception-plume-by-kristin-victoria-barron/",
  },
  {
    id: 66,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "IA's San Francisco Studio: Studio Crawl",
    venue: "IA Interior Architects",
    address: "500 Sansome Street, San Francisco",
    lat: 37.7965,
    lng: -122.4016,
    type: "studio",
    tag: "Open Studio",
    desc: "Explore IA's newly completed 22,000 sq ft double-height SF studio — stadium seating, a speakeasy-inspired lounge, an in-house dog park, and a celebration of San Francisco's vibrant history woven throughout the design.",
    url: "https://sfdesignweek.org/event/ias-san-francisco-studio-studio-crawl/",
  },
  {
    id: 67,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Know Your Roots",
    venue: "Neiman Marcus",
    address: "150 Stockton Street, San Francisco",
    lat: 37.7873,
    lng: -122.4063,
    type: "exhibition",
    tag: "Exhibition",
    desc: "Oakland Roots and Soul Sports Club presents an upcycled fashion window installation — original pieces by CCA designers made from ThredUp upcycled clothing and Oakland Roots jerseys, rooted in Oakland's spirit of resistance and creativity.",
    url: "https://sfdesignweek.org/event/know-your-roots/",
  },
  {
    id: 68,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Bohlin Cywinski Jackson: Studio Crawl",
    venue: "Bohlin Cywinski Jackson",
    address: "49 Geary Street, San Francisco",
    lat: 37.7878,
    lng: -122.4066,
    type: "studio",
    tag: "Open Studio",
    desc: "An evening at BCJ's SF studio exploring new and upcoming work — snacks, refreshments, and a site-specific installation by artist Andy Goldsworthy preserved from the former Haines Gallery during the studio renovation.",
    url: "https://sfdesignweek.org/event/bohlin-cywinski-jackson/",
  },
  {
    id: 69,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Art of Sport. FIFA World Cup 2026",
    venue: "Grumpy's Restaurant & Pub",
    address: "125 Vallejo St, San Francisco",
    lat: 37.7998,
    lng: -122.4039,
    type: "social",
    tag: "Social",
    desc: "Launch of a new collection of 48 World Cup posters by Mucho, JP, and global guest designers — a proper old-fashioned booze up. Beers, posters, and every nation from this year's World Cup on display. Posters available to order online.",
    url: "https://sfdesignweek.org/event/art-of-sport-fifa-world-cup-2026/",
  },
  {
    id: 70,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Hybrid: Curiosity in All Things — Studio Crawl at Stout Books",
    venue: "William Stout Architectural Books",
    address: "804 Montgomery St, San Francisco",
    lat: 37.7977,
    lng: -122.4034,
    type: "social",
    tag: "Social",
    desc: "Hybrid celebrates their book exploring how curiosity drives creative work across disciplines. Copies available for purchase and signing throughout the evening. Curated exhibition of work across branding, environments, and storytelling.",
    url: "https://sfdesignweek.org/event/hybrid-curiosity-in-all-things-studio-crawl-happy-hour-at-stout-books/",
  },
  {
    id: 71,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Multitudes in the Neighborhood: Photography & Art Exhibition",
    venue: "Goodfellas Pizzeria",
    address: "2237 Powell St, San Francisco",
    lat: 37.804,
    lng: -122.4102,
    type: "exhibition",
    tag: "Exhibition",
    desc: "An intimate evening of photography and original artwork at Goodfellas Pizzeria in North Beach — three Bay Area photographers plus painted works by artist Rus, celebrating the culture, communities, and everyday life of the Bay Area.",
    url: "https://sfdesignweek.org/event/multitudes-in-the-neighborhood-a-photography-art-exhibition-at-goodfellas/",
  },
  {
    id: 72,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "CODAME: The New Human",
    venue: "Homebrew Club",
    address: "111 Maiden Lane, San Francisco",
    lat: 37.7878,
    lng: -122.407,
    type: "social",
    tag: "Social/Exhibition",
    desc: "An experiential design event with ARTEX (interactive living art platform) and Print Club (curated art drops). Fireside chat on ART+TECH futures, refreshments, networking, and a limited-edition print raffle. Sober-friendly beverage options.",
    url: "https://sfdesignweek.org/event/codame-the-new-human/",
  },
  {
    id: 73,
    date: "2026-06-12",
    start: "18:00",
    end: "21:00",
    name: "Applied Information Group — Open Studio",
    venue: "Applied Information Group",
    address: "720 Market Street, San Francisco",
    lat: 37.7836,
    lng: -122.4091,
    type: "studio",
    tag: "Open Studio",
    desc: "Meet the Applied Information Group team in their SF studio to learn about wayfinding and experience design as the sun sets over Market Street. Light bites, beverages, and hybrid indoors/outdoors on balconies.",
    url: "https://sfdesignweek.org/event/applied-information-group-open-studio/",
  },
];
